### ISSUE TITLE
Merge w/ `gatsby-plugin-segment-js` ?

### ISSUE THREAD

**Issue by benjaminhoffman** [coreyward/gatsby-plugin-segment-analytics#2]
hey @coreyward !  Cool plugin... curious if you're open to combining efforts into this plugin I created.  It's receiving a lot of community support but definitely could use more.  Segment has so many options and my thought is it's better to have all efforts focused on one plugin to ensure we handle all the use cases

**A lightweight & feature-rich Gatsby plugin to easily add Segment JS snippet to your site.**

https://github.com/benjaminhoffman/gatsby-plugin-segment-js

**Comment by coreyward** [comment]
I created this plugin specifically because gatsby-plugin-segment-js inlines a specific version of Segment rather than using the `createSnippet` routine provided by Segment. 

I don't know that it's worth the headache and confusion that would be caused by replacing gatsby-plugin-segment-js with this code as a new major version. There are philosophical differences between how that plugin handles dev (sending tracking calls to Segment) and how this one does (using a dev shim that doesn't require Segment calls and provides useful information about tracking calls in the console), and this plugin also provides an OutboundLink component that mirrors the behavior of the official gatsby-plugin-google-analytics package.

If you wanted to deprecate gatsby-plugin-segment-js in favor of using gatsby-plugin-segment-analytics that would be fine by me.

**Comment by benjaminhoffman** [comment]
Thanks for the immediate reply @coreyward.  When I worked at Segment, I recall that we encouraged users to _not_ use `createSnippet`.  I just looked it up again to see if the policy has changed and see the [README](https://github.com/segmentio/snippet) states `The recommended way to use analytics.js is to follow the analytics.js quickstart guide. If you absolutely need to generate a snippet dynamically, this is an alternate solution. ` 

Curious why you prefer to use the dynamic snippet?

Regarding dev environment, it's also common practice to have a dev account with Segment.  But you make a very valid point!  Good suggestion.  I'm curious though, could that be implemented as a simple flag on the original plugin vs creating a brand new plugin?

I opened this ticket to see if you would be open to deprecating your plugin in favor of the original one...  I'm happy to integrate your suggestions if those are the only blockers.

(My motivation here is to concentrate resources into one plugin to ensure it packs as much functionality and stability as possible.  The overlap between Gatsby and Segment users is still so small, it may make sense to collaborate vs forking.)

**Comment by coreyward** [comment]
> I just looked it up again to see if the policy has changed and see the [README](https://github.com/segmentio/snippet) states `The recommended way to use analytics.js is to follow the analytics.js quickstart guide. If you absolutely need to generate a snippet dynamically, this is an alternate solution. `
> 
> Curious why you prefer to use the dynamic snippet?

I think directly including the snippet is right for most projects—end users are going to be installing that themselves. For something like a library consumed by other tools, locking everybody to a single version of a third-party dependency tends to cause more people to simply fork or copy the dependency into their codebase to manage.

> I opened this ticket to see if you would be open to deprecating your plugin in favor of the original one... I'm happy to integrate your suggestions if those are the only blockers.
>
> (My motivation here is to concentrate resources into one plugin to ensure it packs as much functionality and stability as possible. The overlap between Gatsby and Segment users is still so small, it may make sense to collaborate vs forking.)

I'll likely keep this plugin independent. It's already built and in-use, and I can continue to maintain easily. My uses would not benefit additional complexity handled by your plugin (e.g. delayed loading or disabling page event tracking), and it is likely that I will continue to extend this to fit other (opinionated) needs. Feel free to incorporate parts of this plugin into your own where you see merit, though.
